baseURL = "https://stultus.in/notes/"
languageCode = "en-us"
title = "stultus notes"
theme = "hugo-digital-garden-theme"
themesdir = "./themes"
copyright = "Hrishikesh Bhaskaran ♥"
relativeURLs = true
canonifyURLs = false

[params]
  name = "Hrishikesh Bhaskaran"
  description = "“I wasn't going to eat it, I was just going to taste it.” - Winnie the Pooh"
  initials = "stultus notes"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "https://x.com/_stultus/"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "https://github.com/stultus"
    icon = "fab fa-github"

  [[params.social]]
    name = "Medium" 
    link = "https://medium.com/@stultus"
    icon = "fab fa-medium-m"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/stultus/"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Website"
    url = "https://stultus.in"
    weight = 1
  [[menu.main]]
    name = "Notes"
    url = "https://stultus.in/notes/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "https://stultus.in/about"
    weight = 3


[taxonomies]
  tag = "tags"


[markup]
  [markup.highlight]
    noClasses = false
    style = 'monokai' # You can choose any built-in style or leave it blank

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true
  notAlternative = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
